name: proyect_porfolio
description: "."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.0.20
  flutter_svg_icons: ^0.0.1+4
  animated_background: ^2.0.0
  lecle_bubble_timeline: ^0.0.1+1
  google_fonts: ^6.2.1
  animate_on_hover: ^1.0.2
  auto_size_text: ^3.0.0
  banner_carousel: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pdf/CurrÃ­culum_Alejandro_Aguilar.pdf

    - assets/svg/linkedin.svg
    - assets/svg/github.svg
    - assets/svg/languageCode.svg

    - assets/images/personal.jpeg
    - assets/images/git.png
    - assets/images/github.png
    - assets/images/intelIj.png

    - assets/images/programLanguage/java.png
    - assets/images/programLanguage/android.png
    - assets/images/programLanguage/maui.png
    - assets/images/programLanguage/html.png
    - assets/images/programLanguage/css.png
    - assets/images/programLanguage/javascript.png
    - assets/images/programLanguage/php.png
    - assets/images/programLanguage/c#.png
    - assets/images/programLanguage/dart.png
    - assets/images/programLanguage/python.png
    - assets/images/programLanguage/kotlin.png
    - assets/images/programLanguage/sprint.png
    - assets/images/programLanguage/flutter.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
