name: proyect_porfolio
description: "."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.2.3
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  url_launcher: ^6.0.20
  animated_background: ^2.0.0
  google_fonts: ^6.2.1
  animate_on_hover: ^1.0.2
  auto_size_text: ^3.0.0
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.10+1
  flutter_svg_icons: ^0.0.1+4
  http: ^1.2.2
  email_validator: ^3.0.0
  flutter_dotenv: ^5.1.0
  flutter_carousel_widget: ^3.0.1
  animate_do: ^4.2.0
  lottie: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  widget_circular_animator: ^1.0.0
  masonry_grid: ^1.0.0
  go_router: ^16.1.0
  web: ^1.1.0
  flutter_widget_from_html: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/pdf/Curriculum_Alejandro_Aguilar_Alba.pdf
    - assets/svg/
    - assets/svg/programLanguage/
    - assets/images/
    - assets/images/certificates/
    - assets/images/projects/tasty/
    - assets/images/projects/goReversi/
    - assets/images/projects/gomoku/
    - assets/images/projects/appStudent/
    - assets/images/projects/appTeacher/
    - assets/images/projects/ultraRestaurant/
    - assets/images/projects/imcCalculator/
    - assets/images/projects/paintVanilla/
    - assets/images/projects/ticTacToe/
    - assets/images/projects/pokeApi/




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
